### ISSUE TITLE
Same problem under debug

### ISSUE THREAD

**Issue by excllent123** [anantapalani/clion-cuda-run-patcher#1]
When I debug the program,I will meet the same problem.
/cmake-build-debug/CMakeFiles/CUDA_Test_Clion.dir/cmake_device_link.o   .. error=13

**Comment by anantapalani** [comment]
This should now be fixed as of v1.1.  The update is pending on JetBrain's servers, but if you don't want to wait you can install the plugin manually by [downloading the .jar](https://github.com/anantapalani/clion-cuda-run-patcher/releases/tag/v1.1). Let me know if it works for you and I'll close this bug.

**Comment by excllent123** [comment]
Hi
   I have update the patcher,It works for me.
   Thanks
