### ISSUE TITLE
Hello! how to use it ?

### ISSUE THREAD

**Issue by bringtree** [anantapalani/clion-cuda-run-patcher#3]
```
Clion 2018.2
macOs 10.13.6
```
Hello !
I am first time to use clion. Can you tell how to apply this patcher in my clion. thanks!

**Comment by anantapalani** [comment]
I only just updated the code to support 2018.2. You can now install it directly inside CLion.

In CLion:
1. go to `File`->`Settings` menu
1. click `Plugins` on the left
1. type `CUDA` in the search text field for `Plugins`
1. click the `Search in repositories` link
1. select `CLion CUDA Run Patcher`
1. click `Install`
1. accept the third-party warning
1. click `Restart CLion` button
1. click `OK` to close `Settings`
1. click `Restart` when prompted

If you ever get the same error again, close the Project and open it again.

Please try this and let me know if it works.
